project_id = "agxpjginfvxfmbypbkmq"

[functions.create-user]
enabled = true
verify_jwt = false
entrypoint = "./functions/create-user/index.ts"

[functions.reset-user-password]
enabled = true
verify_jwt = false
import_map = "./functions/reset-user-password/deno.json"
entrypoint = "./functions/reset-user-password/index.ts"
